<!-- Code Generated by Gabe -->
<?php

// Include the database credentials file to access the database server details.
require_once('../database/db_credentials.php');

// Function to establish a connection to the database
function db_connect() {
    // Create a connection to the MySQL database using credentials from db_credentials.php
    $connection = mysqli_connect(DB_SERVER, DB_USER, DB_PASS, DB_NAME);

    // Check if the connection was successful
    if (mysqli_connect_errno()) {
        // If the connection failed, create an error message with the details
        $msg = "Database connection failed: ";
        $msg = mysqli_connect_error();  // Get the specific error message
        $msg .= " (" . mysqli_connect_errno() . ")";  // Append the error code
        exit($msg);  // Exit the script and display the error message
    }

    // Return the database connection if successful
    return $connection;
}

// Call db_connect to initiate the database connection when this script runs
db_connect();
