<?php

// <!-- Code Generated by Gabe -->
// Define constants for the database connection details

// The database server where the database is hosted.
define("DB_SERVER", "localhost");

// The username to connect to the database.
define("DB_USER", "root");

// The password for the MySQL user.
define("DB_PASS", "");

// The name of the database to connect to.
define("DB_NAME", "pizza_site");
